//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication3.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ManejoError", Namespace="http://schemas.datacontract.org/2004/07/HighChem.SAP.Modelo")]
    [System.SerializableAttribute()]
    public partial class ManejoError : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MetodoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Metodo {
            get {
                return this.MetodoField;
            }
            set {
                if ((object.ReferenceEquals(this.MetodoField, value) != true)) {
                    this.MetodoField = value;
                    this.RaisePropertyChanged("Metodo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Documento", Namespace="http://schemas.datacontract.org/2004/07/HighChem.SAP.Modelo")]
    [System.SerializableAttribute()]
    public partial class Documento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CondicionPagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FecaDocField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaActualizadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaCargaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FolioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdVentdedorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ImpuestoDLSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ImpuestoMNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MercadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MonedaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NegocioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProveedorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double SubTotalDLSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double SubTotalMNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SucursalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipodeCambioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TotalDLSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TotalMNField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CondicionPago {
            get {
                return this.CondicionPagoField;
            }
            set {
                if ((object.ReferenceEquals(this.CondicionPagoField, value) != true)) {
                    this.CondicionPagoField = value;
                    this.RaisePropertyChanged("CondicionPago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FecaDoc {
            get {
                return this.FecaDocField;
            }
            set {
                if ((object.ReferenceEquals(this.FecaDocField, value) != true)) {
                    this.FecaDocField = value;
                    this.RaisePropertyChanged("FecaDoc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaActualizado {
            get {
                return this.FechaActualizadoField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaActualizadoField, value) != true)) {
                    this.FechaActualizadoField = value;
                    this.RaisePropertyChanged("FechaActualizado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaCarga {
            get {
                return this.FechaCargaField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaCargaField, value) != true)) {
                    this.FechaCargaField = value;
                    this.RaisePropertyChanged("FechaCarga");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaCreacion {
            get {
                return this.FechaCreacionField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaCreacionField, value) != true)) {
                    this.FechaCreacionField = value;
                    this.RaisePropertyChanged("FechaCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Folio {
            get {
                return this.FolioField;
            }
            set {
                if ((object.ReferenceEquals(this.FolioField, value) != true)) {
                    this.FolioField = value;
                    this.RaisePropertyChanged("Folio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdCliente {
            get {
                return this.IdClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.IdClienteField, value) != true)) {
                    this.IdClienteField = value;
                    this.RaisePropertyChanged("IdCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdVentdedor {
            get {
                return this.IdVentdedorField;
            }
            set {
                if ((object.ReferenceEquals(this.IdVentdedorField, value) != true)) {
                    this.IdVentdedorField = value;
                    this.RaisePropertyChanged("IdVentdedor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ImpuestoDLS {
            get {
                return this.ImpuestoDLSField;
            }
            set {
                if ((this.ImpuestoDLSField.Equals(value) != true)) {
                    this.ImpuestoDLSField = value;
                    this.RaisePropertyChanged("ImpuestoDLS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ImpuestoMN {
            get {
                return this.ImpuestoMNField;
            }
            set {
                if ((this.ImpuestoMNField.Equals(value) != true)) {
                    this.ImpuestoMNField = value;
                    this.RaisePropertyChanged("ImpuestoMN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mercado {
            get {
                return this.MercadoField;
            }
            set {
                if ((object.ReferenceEquals(this.MercadoField, value) != true)) {
                    this.MercadoField = value;
                    this.RaisePropertyChanged("Mercado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Moneda {
            get {
                return this.MonedaField;
            }
            set {
                if ((object.ReferenceEquals(this.MonedaField, value) != true)) {
                    this.MonedaField = value;
                    this.RaisePropertyChanged("Moneda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Negocio {
            get {
                return this.NegocioField;
            }
            set {
                if ((object.ReferenceEquals(this.NegocioField, value) != true)) {
                    this.NegocioField = value;
                    this.RaisePropertyChanged("Negocio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Proveedor {
            get {
                return this.ProveedorField;
            }
            set {
                if ((object.ReferenceEquals(this.ProveedorField, value) != true)) {
                    this.ProveedorField = value;
                    this.RaisePropertyChanged("Proveedor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double SubTotalDLS {
            get {
                return this.SubTotalDLSField;
            }
            set {
                if ((this.SubTotalDLSField.Equals(value) != true)) {
                    this.SubTotalDLSField = value;
                    this.RaisePropertyChanged("SubTotalDLS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double SubTotalMN {
            get {
                return this.SubTotalMNField;
            }
            set {
                if ((this.SubTotalMNField.Equals(value) != true)) {
                    this.SubTotalMNField = value;
                    this.RaisePropertyChanged("SubTotalMN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sucursal {
            get {
                return this.SucursalField;
            }
            set {
                if ((object.ReferenceEquals(this.SucursalField, value) != true)) {
                    this.SucursalField = value;
                    this.RaisePropertyChanged("Sucursal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoDocumento {
            get {
                return this.TipoDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoDocumentoField, value) != true)) {
                    this.TipoDocumentoField = value;
                    this.RaisePropertyChanged("TipoDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipodeCambio {
            get {
                return this.TipodeCambioField;
            }
            set {
                if ((object.ReferenceEquals(this.TipodeCambioField, value) != true)) {
                    this.TipodeCambioField = value;
                    this.RaisePropertyChanged("TipodeCambio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double TotalDLS {
            get {
                return this.TotalDLSField;
            }
            set {
                if ((this.TotalDLSField.Equals(value) != true)) {
                    this.TotalDLSField = value;
                    this.RaisePropertyChanged("TotalDLS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double TotalMN {
            get {
                return this.TotalMNField;
            }
            set {
                if ((this.TotalMNField.Equals(value) != true)) {
                    this.TotalMNField = value;
                    this.RaisePropertyChanged("TotalMN");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentoDetalle", Namespace="http://schemas.datacontract.org/2004/07/HighChem.SAP.Modelo")]
    [System.SerializableAttribute()]
    public partial class DocumentoDetalle : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaActualizadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaCargaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FolioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdVentdedorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ImporteDLSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ImporteMNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MonedaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PriceDLSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PriceMNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RenglonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipodeCambioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaActualizado {
            get {
                return this.FechaActualizadoField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaActualizadoField, value) != true)) {
                    this.FechaActualizadoField = value;
                    this.RaisePropertyChanged("FechaActualizado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaCarga {
            get {
                return this.FechaCargaField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaCargaField, value) != true)) {
                    this.FechaCargaField = value;
                    this.RaisePropertyChanged("FechaCarga");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaCreacion {
            get {
                return this.FechaCreacionField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaCreacionField, value) != true)) {
                    this.FechaCreacionField = value;
                    this.RaisePropertyChanged("FechaCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Folio {
            get {
                return this.FolioField;
            }
            set {
                if ((object.ReferenceEquals(this.FolioField, value) != true)) {
                    this.FolioField = value;
                    this.RaisePropertyChanged("Folio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdVentdedor {
            get {
                return this.IdVentdedorField;
            }
            set {
                if ((object.ReferenceEquals(this.IdVentdedorField, value) != true)) {
                    this.IdVentdedorField = value;
                    this.RaisePropertyChanged("IdVentdedor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ImporteDLS {
            get {
                return this.ImporteDLSField;
            }
            set {
                if ((this.ImporteDLSField.Equals(value) != true)) {
                    this.ImporteDLSField = value;
                    this.RaisePropertyChanged("ImporteDLS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ImporteMN {
            get {
                return this.ImporteMNField;
            }
            set {
                if ((this.ImporteMNField.Equals(value) != true)) {
                    this.ImporteMNField = value;
                    this.RaisePropertyChanged("ImporteMN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Moneda {
            get {
                return this.MonedaField;
            }
            set {
                if ((object.ReferenceEquals(this.MonedaField, value) != true)) {
                    this.MonedaField = value;
                    this.RaisePropertyChanged("Moneda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PriceDLS {
            get {
                return this.PriceDLSField;
            }
            set {
                if ((this.PriceDLSField.Equals(value) != true)) {
                    this.PriceDLSField = value;
                    this.RaisePropertyChanged("PriceDLS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PriceMN {
            get {
                return this.PriceMNField;
            }
            set {
                if ((this.PriceMNField.Equals(value) != true)) {
                    this.PriceMNField = value;
                    this.RaisePropertyChanged("PriceMN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Producto {
            get {
                return this.ProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductoField, value) != true)) {
                    this.ProductoField = value;
                    this.RaisePropertyChanged("Producto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Renglon {
            get {
                return this.RenglonField;
            }
            set {
                if ((this.RenglonField.Equals(value) != true)) {
                    this.RenglonField = value;
                    this.RaisePropertyChanged("Renglon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoDocumento {
            get {
                return this.TipoDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoDocumentoField, value) != true)) {
                    this.TipoDocumentoField = value;
                    this.RaisePropertyChanged("TipoDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipodeCambio {
            get {
                return this.TipodeCambioField;
            }
            set {
                if ((object.ReferenceEquals(this.TipodeCambioField, value) != true)) {
                    this.TipodeCambioField = value;
                    this.RaisePropertyChanged("TipodeCambio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://schemas.datacontract.org/2004/07/HighChem.SAP.Modelo")]
    [System.SerializableAttribute()]
    public partial class Cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CiudadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaActualizadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdVendedorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MercadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RFCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RazonSocField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SucursalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ciudad {
            get {
                return this.CiudadField;
            }
            set {
                if ((object.ReferenceEquals(this.CiudadField, value) != true)) {
                    this.CiudadField = value;
                    this.RaisePropertyChanged("Ciudad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaActualizado {
            get {
                return this.FechaActualizadoField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaActualizadoField, value) != true)) {
                    this.FechaActualizadoField = value;
                    this.RaisePropertyChanged("FechaActualizado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaCreacion {
            get {
                return this.FechaCreacionField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaCreacionField, value) != true)) {
                    this.FechaCreacionField = value;
                    this.RaisePropertyChanged("FechaCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdCliente {
            get {
                return this.IdClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.IdClienteField, value) != true)) {
                    this.IdClienteField = value;
                    this.RaisePropertyChanged("IdCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdVendedor {
            get {
                return this.IdVendedorField;
            }
            set {
                if ((object.ReferenceEquals(this.IdVendedorField, value) != true)) {
                    this.IdVendedorField = value;
                    this.RaisePropertyChanged("IdVendedor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mercado {
            get {
                return this.MercadoField;
            }
            set {
                if ((object.ReferenceEquals(this.MercadoField, value) != true)) {
                    this.MercadoField = value;
                    this.RaisePropertyChanged("Mercado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pais {
            get {
                return this.PaisField;
            }
            set {
                if ((object.ReferenceEquals(this.PaisField, value) != true)) {
                    this.PaisField = value;
                    this.RaisePropertyChanged("Pais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RFC {
            get {
                return this.RFCField;
            }
            set {
                if ((object.ReferenceEquals(this.RFCField, value) != true)) {
                    this.RFCField = value;
                    this.RaisePropertyChanged("RFC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RazonSoc {
            get {
                return this.RazonSocField;
            }
            set {
                if ((object.ReferenceEquals(this.RazonSocField, value) != true)) {
                    this.RazonSocField = value;
                    this.RaisePropertyChanged("RazonSoc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sucursal {
            get {
                return this.SucursalField;
            }
            set {
                if ((object.ReferenceEquals(this.SucursalField, value) != true)) {
                    this.SucursalField = value;
                    this.RaisePropertyChanged("Sucursal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Producto", Namespace="http://schemas.datacontract.org/2004/07/HighChem.SAP.Modelo")]
    [System.SerializableAttribute()]
    public partial class Producto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClasificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaveSAPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaActualizadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdProveedorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NegocioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnidadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Categoria {
            get {
                return this.CategoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoriaField, value) != true)) {
                    this.CategoriaField = value;
                    this.RaisePropertyChanged("Categoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Clasificacion {
            get {
                return this.ClasificacionField;
            }
            set {
                if ((object.ReferenceEquals(this.ClasificacionField, value) != true)) {
                    this.ClasificacionField = value;
                    this.RaisePropertyChanged("Clasificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClaveSAP {
            get {
                return this.ClaveSAPField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaveSAPField, value) != true)) {
                    this.ClaveSAPField = value;
                    this.RaisePropertyChanged("ClaveSAP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaActualizado {
            get {
                return this.FechaActualizadoField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaActualizadoField, value) != true)) {
                    this.FechaActualizadoField = value;
                    this.RaisePropertyChanged("FechaActualizado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaCreacion {
            get {
                return this.FechaCreacionField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaCreacionField, value) != true)) {
                    this.FechaCreacionField = value;
                    this.RaisePropertyChanged("FechaCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdProveedor {
            get {
                return this.IdProveedorField;
            }
            set {
                if ((object.ReferenceEquals(this.IdProveedorField, value) != true)) {
                    this.IdProveedorField = value;
                    this.RaisePropertyChanged("IdProveedor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Negocio {
            get {
                return this.NegocioField;
            }
            set {
                if ((object.ReferenceEquals(this.NegocioField, value) != true)) {
                    this.NegocioField = value;
                    this.RaisePropertyChanged("Negocio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Unidad {
            get {
                return this.UnidadField;
            }
            set {
                if ((object.ReferenceEquals(this.UnidadField, value) != true)) {
                    this.UnidadField = value;
                    this.RaisePropertyChanged("Unidad");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://HighChem.SAP.WebService/2014/06/", ConfigurationName="ServiceReference1.SapService")]
    public interface SapService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://HighChem.SAP.WebService/2014/06/SapService/Autenticacion", ReplyAction="http://HighChem.SAP.WebService/2014/06/SapService/AutenticacionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WindowsFormsApplication3.ServiceReference1.ManejoError), Action="http://HighChem.SAP.WebService/2014/06/SapService/AutenticacionManejoErrorFault", Name="ManejoError", Namespace="http://schemas.datacontract.org/2004/07/HighChem.SAP.Modelo")]
        string Autenticacion(string pidUser, string pcontrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://HighChem.SAP.WebService/2014/06/SapService/Autenticacion", ReplyAction="http://HighChem.SAP.WebService/2014/06/SapService/AutenticacionResponse")]
        System.Threading.Tasks.Task<string> AutenticacionAsync(string pidUser, string pcontrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://HighChem.SAP.WebService/2014/06/SapService/Documento", ReplyAction="http://HighChem.SAP.WebService/2014/06/SapService/DocumentoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WindowsFormsApplication3.ServiceReference1.ManejoError), Action="http://HighChem.SAP.WebService/2014/06/SapService/DocumentoManejoErrorFault", Name="ManejoError", Namespace="http://schemas.datacontract.org/2004/07/HighChem.SAP.Modelo")]
        WindowsFormsApplication3.ServiceReference1.Documento[] Documento(string pidSession, string pfechaInicio, string pfechaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://HighChem.SAP.WebService/2014/06/SapService/Documento", ReplyAction="http://HighChem.SAP.WebService/2014/06/SapService/DocumentoResponse")]
        System.Threading.Tasks.Task<WindowsFormsApplication3.ServiceReference1.Documento[]> DocumentoAsync(string pidSession, string pfechaInicio, string pfechaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://HighChem.SAP.WebService/2014/06/SapService/DocumentoDetalle", ReplyAction="http://HighChem.SAP.WebService/2014/06/SapService/DocumentoDetalleResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WindowsFormsApplication3.ServiceReference1.ManejoError), Action="http://HighChem.SAP.WebService/2014/06/SapService/DocumentoDetalleManejoErrorFaul" +
            "t", Name="ManejoError", Namespace="http://schemas.datacontract.org/2004/07/HighChem.SAP.Modelo")]
        WindowsFormsApplication3.ServiceReference1.DocumentoDetalle[] DocumentoDetalle(string pidSession, string pfechaInicio, string pfechaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://HighChem.SAP.WebService/2014/06/SapService/DocumentoDetalle", ReplyAction="http://HighChem.SAP.WebService/2014/06/SapService/DocumentoDetalleResponse")]
        System.Threading.Tasks.Task<WindowsFormsApplication3.ServiceReference1.DocumentoDetalle[]> DocumentoDetalleAsync(string pidSession, string pfechaInicio, string pfechaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://HighChem.SAP.WebService/2014/06/SapService/Clientes", ReplyAction="http://HighChem.SAP.WebService/2014/06/SapService/ClientesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WindowsFormsApplication3.ServiceReference1.ManejoError), Action="http://HighChem.SAP.WebService/2014/06/SapService/ClientesManejoErrorFault", Name="ManejoError", Namespace="http://schemas.datacontract.org/2004/07/HighChem.SAP.Modelo")]
        WindowsFormsApplication3.ServiceReference1.Cliente[] Clientes(string pidSession, string pfechaInicio, string pfechaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://HighChem.SAP.WebService/2014/06/SapService/Clientes", ReplyAction="http://HighChem.SAP.WebService/2014/06/SapService/ClientesResponse")]
        System.Threading.Tasks.Task<WindowsFormsApplication3.ServiceReference1.Cliente[]> ClientesAsync(string pidSession, string pfechaInicio, string pfechaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://HighChem.SAP.WebService/2014/06/SapService/Productos", ReplyAction="http://HighChem.SAP.WebService/2014/06/SapService/ProductosResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WindowsFormsApplication3.ServiceReference1.ManejoError), Action="http://HighChem.SAP.WebService/2014/06/SapService/ProductosManejoErrorFault", Name="ManejoError", Namespace="http://schemas.datacontract.org/2004/07/HighChem.SAP.Modelo")]
        WindowsFormsApplication3.ServiceReference1.Producto[] Productos(string pidSession, string pfechaInicio, string pfechaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://HighChem.SAP.WebService/2014/06/SapService/Productos", ReplyAction="http://HighChem.SAP.WebService/2014/06/SapService/ProductosResponse")]
        System.Threading.Tasks.Task<WindowsFormsApplication3.ServiceReference1.Producto[]> ProductosAsync(string pidSession, string pfechaInicio, string pfechaFin);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SapServiceChannel : WindowsFormsApplication3.ServiceReference1.SapService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SapServiceClient : System.ServiceModel.ClientBase<WindowsFormsApplication3.ServiceReference1.SapService>, WindowsFormsApplication3.ServiceReference1.SapService {
        
        public SapServiceClient() {
        }
        
        public SapServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SapServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SapServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SapServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Autenticacion(string pidUser, string pcontrasena) {
            return base.Channel.Autenticacion(pidUser, pcontrasena);
        }
        
        public System.Threading.Tasks.Task<string> AutenticacionAsync(string pidUser, string pcontrasena) {
            return base.Channel.AutenticacionAsync(pidUser, pcontrasena);
        }
        
        public WindowsFormsApplication3.ServiceReference1.Documento[] Documento(string pidSession, string pfechaInicio, string pfechaFin) {
            return base.Channel.Documento(pidSession, pfechaInicio, pfechaFin);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication3.ServiceReference1.Documento[]> DocumentoAsync(string pidSession, string pfechaInicio, string pfechaFin) {
            return base.Channel.DocumentoAsync(pidSession, pfechaInicio, pfechaFin);
        }
        
        public WindowsFormsApplication3.ServiceReference1.DocumentoDetalle[] DocumentoDetalle(string pidSession, string pfechaInicio, string pfechaFin) {
            return base.Channel.DocumentoDetalle(pidSession, pfechaInicio, pfechaFin);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication3.ServiceReference1.DocumentoDetalle[]> DocumentoDetalleAsync(string pidSession, string pfechaInicio, string pfechaFin) {
            return base.Channel.DocumentoDetalleAsync(pidSession, pfechaInicio, pfechaFin);
        }
        
        public WindowsFormsApplication3.ServiceReference1.Cliente[] Clientes(string pidSession, string pfechaInicio, string pfechaFin) {
            return base.Channel.Clientes(pidSession, pfechaInicio, pfechaFin);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication3.ServiceReference1.Cliente[]> ClientesAsync(string pidSession, string pfechaInicio, string pfechaFin) {
            return base.Channel.ClientesAsync(pidSession, pfechaInicio, pfechaFin);
        }
        
        public WindowsFormsApplication3.ServiceReference1.Producto[] Productos(string pidSession, string pfechaInicio, string pfechaFin) {
            return base.Channel.Productos(pidSession, pfechaInicio, pfechaFin);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication3.ServiceReference1.Producto[]> ProductosAsync(string pidSession, string pfechaInicio, string pfechaFin) {
            return base.Channel.ProductosAsync(pidSession, pfechaInicio, pfechaFin);
        }
    }
}
